# @package _global_

# defaults:
#   - override /model: dual_encoder
#   - override /data: test
#   - override /lightning: default
#   - override /callbacks: test
#   - override /logger: wandb
  # - _self_

callbacks:
  zeroshot: null
  linear_probe:
    input_dim: 768
    logging_interval: 'epoch'
    log_every: 1
    confusion_matrix: True
    verbose: True
    max_epochs: 100
    top_k: [1,3,5]
    learning_rates: [0.1, 0.01, 0.001]

data:
  datasets:
    - "Caltech101"
    