# 32yprt3g:
#   image_encoder: google/vit-base-patch16-224
#   name: SimCLR
#   subset_fraction: 0.4
#   color: black
# xarqrl5t:
#   image_encoder: google/vit-base-patch16-224
#   name: SimCLR + ITM
#   subset_fraction: 0.4
#   color: blue
# 5ib9fce5:
#   image_encoder: google/vit-base-patch16-224
#   name: CLIP + SimCLR
#   subset_fraction: 0.4
#   color: green
# 3b3zvcnp:
#   image_encoder: google/vit-base-patch16-224
#   name: CLIP + SimCLR + ITM
#   subset_fraction: 0.4
#   color: orange
# ogi7d638:
#   image_encoder: google/vit-base-patch16-224
#   name: CLIP + ITM
#   subset_fraction: 0.4
#   color: pink
# 6z9rakfu:
#   image_encoder: google/vit-base-patch16-224
#   name: CLIP
#   subset_fraction: 0.4
#   color: red
# udtu05nw:
#   image_encoder: google/vit-base-patch16-224
#   name: SimCLR
#   subset_fraction: 0.2
#   color: black
# 8el3y1x8:
#   image_encoder: google/vit-base-patch16-224
#   name: SimCLR + ITM
#   subset_fraction: 0.2
#   color: blue
# u5l6rwc4:
#   image_encoder: google/vit-base-patch16-224
#   name: CLIP + SimCLR
#   subset_fraction: 0.2
#   color: green
# d4112qkb:
#   image_encoder: google/vit-base-patch16-224
#   name: CLIP + SimCLR + ITM
#   subset_fraction: 0.2
#   color: orange
# gh3j06nh:
#   image_encoder: google/vit-base-patch16-224
#   name: CLIP + ITM
#   subset_fraction: 0.2
#   color: pink
# n5trwpk9:
#   image_encoder: google/vit-base-patch16-224
#   name: CLIP
#   subset_fraction: 0.2
#   color: red
hd0d88w6:
  image_encoder: google/vit-base-patch16-224
  model: SimCLR
  subset_fraction: 0.1
2ctuh8qt:
  image_encoder: google/vit-base-patch16-224
  model: SimCLR + ITM
  subset_fraction: 0.1
e35tvg9i:
  image_encoder: google/vit-base-patch16-224
  model: CLIP + SimCLR
  subset_fraction: 0.1
jgjh5o3y:
  image_encoder: google/vit-base-patch16-224
  model: CLIP
  subset_fraction: 0.1
usf43diq:
  image_encoder: google/vit-base-patch16-224
  model: CLIP + SimCLR + ITM
  subset_fraction: 0.1
v7kw2sco:
  image_encoder: google/vit-base-patch16-224
  model: CLIP + ITM
  subset_fraction: 0.1
c5v74o65:
  image_encoder: google/vit-base-patch16-224
  model: SimCLR
  subset_fraction: 0.05
668yutoa:
  image_encoder: google/vit-base-patch16-224
  model: SimCLR + ITM
  subset_fraction: 0.05
07xhwbwd:
  image_encoder: google/vit-base-patch16-224
  model: CLIP + SimCLR + ITM
  subset_fraction: 0.05
8gpipykd:
  image_encoder: google/vit-base-patch16-224
  model: CLIP + ITM
  subset_fraction: 0.05
f19vtgpv:
  image_encoder: google/vit-base-patch16-224
  model: CLIP + SimCLR
  subset_fraction: 0.05
pllfz8k6:
  image_encoder: google/vit-base-patch16-224
  model: CLIP
  subset_fraction: 0.05
