#resume_checkpoint: '/home/phisch/multimodal/models/cliplike/ckpts/5m917c9w/last.ckpt'

save_dir: './models/cliplike/'

# wandb args
wandb:
  offline: True
  #name: 
  tags : ['clip', 'coco', 'vg', 'cc', 'cifar10', 'pretrained weights']
  #group: 'debug'
  group: 'test'
  #group: 'run'
  #group: 'clip'
  project : 'multimodal'
  dir : './wandb/'
  ### checkpoint args
  #id: 5m917c9w


lightning:
  seed : 69
  trainer:
    fast_dev_run: True
    #overfit_batches: 5 #5
    val_check_interval: 1 #0.3
    log_every_n_steps: 1 #4 #5 #10
    #devices: 2  #[01] #[3] #[0 1]
    accelerator: 'auto'
    #strategy: 'ddp' #'ddp_find_unused_parameters_true' #'ddp_cpu'
    deterministic: True
    #precision: '16-mixed'
    gradient_clip_algorithm: "norm"
    gradient_clip_val: 1.0
    max_epochs: 50 #100
    # num_nodes : 4   
  model_checkpoint_callback:
    every_n_epochs: 1
    save_last: True
    save_top_k: 2
  cifar_linear_probe_callback:
    logging_interval: 'epoch'
    log_every: 3
    confusion_matrix: True
    verbose: False
    max_epochs: 400
  cifar_zeroshot_callback:
    use_subset: True
    subset_fraction: 0.01

gradient_checkpointing: True

zeroshot:
  templates:
    - 'a photo of a {}.'
    - 'a blurry photo of a {}.'
    - 'a black and white photo of a {}.'
    - 'a low contrast photo of a {}.'
    - 'a high contrast photo of a {}.'
    - 'a bad photo of a {}.'
    - 'a good photo of a {}.'
    - 'a photo of a small {}.'
    - 'a photo of a big {}.'
    - 'a photo of the {}.'
    - 'a blurry photo of the {}.'
    - 'a black and white photo of the {}.'
    - 'a low contrast photo of the {}.'
    - 'a high contrast photo of the {}.'
    - 'a bad photo of the {}.'
    - 'a good photo of the {}.'
    - 'a photo of the small {}.'
    - 'a photo of the big {}.'

dataloader:
  train:
    shuffle : True
    #batch_size : 2048  #896 #960 #1024 #256 #180
    batch_size : 12
    num_workers : 1
    persistent_workers : True
    pin_memory: True

  coco_val:
    shuffle : False
    batch_size : 12 
    #batch_size : 2048 #896 #960 #1024 #256 #180
    num_workers : 1
    persistent_workers : True
    pin_memory: True
  
  cifar10_val:
    batch_size: 12
    shuffle: False
    num_workers: 1
    #persistent_workers: True
    pin_memory: True

  caltech101_val:
    batch_size: 12
    shuffle: False
    num_workers: 1
    #persistent_workers: True
    pin_memory: True



loss:
  losses:
    - 'contrastive'
    - 'image_text_matching'
    - 'SimCLR'
  contrastive:
  #  temperature : 1.
  image_text_matching:
    arg1: ''
  simclr:
    # temperature:
    # learn_temperature: True



optimizer:
  name : "AdamW"
  lr: 1e-04
  kwargs:
    weight_decay : 0.005
    betas : [0.90, 0.95]


# scheduler:
#   name:
#     - 'CosineWarmup'
#     #- 'CosineWarmupHardRestarts'
#   kwargs:
#     #T_max : 1000
#     num_warmup_steps: 'epoch'
#     num_training_steps: 'all' #20000
#     #num_cycles: 10
#     initial_lr: 1e-08
#  interval: "step"

scheduler:
  name: CosineWarmup
  monitor: 'loss-val/dataloader_idx_0'
  interval: 'step'
  kwargs:
    initial_lr: 1e-08
    num_warmup_steps: 'epoch'
    num_training_steps: 'all'



model:
  #image_encoder_name : 'openai/clip-vit-base-patch32'
  #text_encoder_name : 'openai/clip-vit-base-patch32'
  image_encoder_name : 'google/vit-base-patch16-224'
  text_encoder_name : 'google-bert/bert-base-uncased'
  tokenizer :
    use_fast: False
  


dataset:
  train:
    - 'coco'
    # - 'vg'
    # - 'cc3m'
  val:
    - 'coco_val'
    - 'cifar10_val'
    - 'caltech101_val'
  transforms:
    RandAugment:
      num_ops: 3
      magnitude: 8
  max_seq_length: 72
  coco:
    data_dir : 'C:\Users\sadua\OneDrive\Dokumente\Studium\Masterarbeit\Multimodal Learning\data\coco'
    split_train : './my_datasets/coco_karpathy_train.json'
    split_val : './my_datasets/coco_karpathy_val.json'
    split_test : './my_datasets/coco_karpathy_test.json'
  vg:
    data_dir: '/pfss/mlde/workspaces/mlde_wsp_PI_Roig/shared/datasets/VG_Bhavin/VG'
  cc3m:
    data_dir: '/pfss/mlde/workspaces/mlde_wsp_PI_Roig/shared/datasets/CC3m/'
  



  
  #train_image_dir : 'C:/Users/sadua/OneDrive/Dokumente/Studium/Masterarbeit/Multimodal Learning/data/coco/train2014'
  #val_image_dir : 'C:/Users/sadua/OneDrive/Dokumente/Studium/Masterarbeit/Multimodal Learning/data/coco/val2014'
  # dataset_name : 'AC_'
  # kwargs:
  #   frame_ids : 'center'
  #   return_image : True
  #   return_audio : False
  #   return_captions_visual : True
  #   return_captions_auditory : False
