# @package _global_

defaults:
  - model: dual_encoder
  - data: test
  - lightning: default
  - callbacks/zeroshot: template_sets_and_itm
  - callbacks/linear_probe: null
  - loss: default
  - optimizer: default
  - scheduler: default
  - paths: g4
  - logger: wandb
  - checkpoints: full_dataset #full_dataset_aug_mlm
  - debug: null
  - _self_
  - custom_run: null

device: ???

lightning:
  trainer:
    devices: ${device}

result_subdir: "zero_shot/CLIP+SimCLR-lower_aug"
result_file_suffix: ''

callbacks:
  zeroshot:
    use_itm_head: True
    callback:
      only_itm: False

