strategy: 'auto'
fast_dev_run: False #True #False #True #False
#overfit_batches: 1
#val_check_interval: 0.3
log_every_n_steps: 1 #5 #10
max_epochs: 1
devices: ??? #[3] #[3]    #[01] #[3] #[0 1]
num_nodes: 1
accelerator: 'gpu'
deterministic: 'warn' #True
precision: '16-mixed'
gradient_clip_algorithm: "norm"
gradient_clip_val: 1.0   
# static_graph: True #False #True #False #True
