c5v74o65:
  image_encoder: google/vit-base-patch16-224
  model: SimCLR
  subset_fraction: 0.05
668yutoa:
  image_encoder: google/vit-base-patch16-224
  model: SimCLR + ITM
  subset_fraction: 0.05
07xhwbwd:
  image_encoder: google/vit-base-patch16-224
  model: CLIP + SimCLR + ITM
  subset_fraction: 0.05
8gpipykd:
  image_encoder: google/vit-base-patch16-224
  model: CLIP + ITM
  subset_fraction: 0.05
f19vtgpv:
  image_encoder: google/vit-base-patch16-224
  model: CLIP + SimCLR
  subset_fraction: 0.05
pllfz8k6:
  image_encoder: google/vit-base-patch16-224
  model: CLIP
  subset_fraction: 0.05
