SimCLR:
  udtu05nw:
    subset_fraction: 0.2
  08q77hgf:
  32yprt3g:
  e2kwl0iu:
  nq3c74wi:
  
  zathvtrx:
SimCLR + ITM:
  03avtdyk:
  8el3y1x8:
  8estzlel:
  9v1wy0vb:
  ojnkbbrd:
  xarqrl5t:
CLIP + SimCLR:
  1j1wb3o6:
  5ib9fce5:
  bz3dvkm5:
  oc0g8fql:
  qkk0yi2q:
  u5l6rwc4:
CLIP + SimCLR + ITM:
  2k0xgnrt:
  3b3zvcnp:
  95qxia4w:
  9nvg456i:
  d4112qkb:
  x7kjrc29:
CLIP + ITM:
  2udboe06:
  93t3xgrr:
  gh3j06nh:
  kx1devsu:
  ogi7d638:
  v8r6ibfz:
CLIP:
  6gvnn76i:
  6z9rakfu:
  ps81urf1:
  yh1adr3g:
